import {
  Folder,
  FolderKanban,
  FolderOpen,
  FolderGit,
  FolderHeart,
  FolderKey,
  FolderSearch,
  Rocket,
  Zap,
  Star,
  Heart,
  Target,
  Flag,
  Bookmark,
  Briefcase,
  Users,
  Code,
  Globe,
  Lightbulb,
  Activity,
  Archive,
  Award,
  Banknote,
  Beaker,
  Bell,
  Book,
  BookOpen,
  Bot,
  Box,
  Brain,
  Bug,
  Building,
  Building2,
  Cake,
  Calendar,
  Camera,
  Clipboard,
  Clock,
  Cloud,
  Coffee,
  Cog,
  Compass,
  CreditCard,
  Crown,
  Database,
  Diamond,
  DollarSign,
  Droplet,
  Dumbbell,
  Flame,
  FlaskConical,
  Flower,
  Gamepad2,
  Gem,
  Gift,
  Hammer,
  Headphones,
  HeartPulse,
  Home,
  Image,
  Inbox,
  Key,
  Laptop,
  Layers,
  Layout,
  Leaf,
  Library,
  LifeBuoy,
  Lock,
  Mail,
  Map,
  Megaphone,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Plane,
  Play,
  Puzzle,
  Rainbow,
  Receipt,
  Ruler,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Store,
  Sun,
  Tablet,
  Tag,
  Terminal,
  ThumbsUp,
  Timer,
  TreeDeciduous,
  Truck,
  University,
  Video,
  Wallet,
  Wand,
  Watch,
  Wifi,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

// Predefined colors for projects
export const PROJECT_COLORS = [
  "#6366f1", // Indigo
  "#8b5cf6", // Violet
  "#ec4899", // Pink
  "#ef4444", // Red
  "#f97316", // Orange
  "#eab308", // Yellow
  "#22c55e", // Green
  "#14b8a6", // Teal
  "#06b6d4", // Cyan
  "#3b82f6", // Blue
];

// Project icons map (80 icons)
export const PROJECT_ICONS: { id: string; icon: LucideIcon; label: string }[] =
  [
    // Folders
    { id: "folder", icon: Folder, label: "Folder" },
    { id: "folder-kanban", icon: FolderKanban, label: "Kanban" },
    { id: "folder-open", icon: FolderOpen, label: "Open Folder" },
    { id: "folder-git", icon: FolderGit, label: "Git" },
    { id: "folder-heart", icon: FolderHeart, label: "Favorites" },
    { id: "folder-key", icon: FolderKey, label: "Secure" },
    { id: "folder-search", icon: FolderSearch, label: "Search" },
    // Common
    { id: "rocket", icon: Rocket, label: "Rocket" },
    { id: "zap", icon: Zap, label: "Zap" },
    { id: "star", icon: Star, label: "Star" },
    { id: "heart", icon: Heart, label: "Heart" },
    { id: "target", icon: Target, label: "Target" },
    { id: "flag", icon: Flag, label: "Flag" },
    { id: "bookmark", icon: Bookmark, label: "Bookmark" },
    { id: "briefcase", icon: Briefcase, label: "Briefcase" },
    { id: "users", icon: Users, label: "Users" },
    { id: "code", icon: Code, label: "Code" },
    { id: "globe", icon: Globe, label: "Globe" },
    { id: "lightbulb", icon: Lightbulb, label: "Lightbulb" },
    // Business
    { id: "building", icon: Building, label: "Building" },
    { id: "building2", icon: Building2, label: "Office" },
    { id: "banknote", icon: Banknote, label: "Money" },
    { id: "credit-card", icon: CreditCard, label: "Payment" },
    { id: "dollar-sign", icon: DollarSign, label: "Dollar" },
    { id: "receipt", icon: Receipt, label: "Receipt" },
    { id: "wallet", icon: Wallet, label: "Wallet" },
    { id: "store", icon: Store, label: "Store" },
    { id: "shopping-cart", icon: ShoppingCart, label: "Cart" },
    { id: "shopping-bag", icon: ShoppingBag, label: "Shopping" },
    // Tech
    { id: "laptop", icon: Laptop, label: "Laptop" },
    { id: "monitor", icon: Monitor, label: "Monitor" },
    { id: "smartphone", icon: Smartphone, label: "Mobile" },
    { id: "tablet", icon: Tablet, label: "Tablet" },
    { id: "server", icon: Server, label: "Server" },
    { id: "database", icon: Database, label: "Database" },
    { id: "terminal", icon: Terminal, label: "Terminal" },
    { id: "bug", icon: Bug, label: "Bug" },
    { id: "bot", icon: Bot, label: "Bot" },
    { id: "brain", icon: Brain, label: "AI" },
    { id: "cloud", icon: Cloud, label: "Cloud" },
    { id: "wifi", icon: Wifi, label: "Wifi" },
    // Creative
    { id: "palette", icon: Palette, label: "Design" },
    { id: "pen-tool", icon: PenTool, label: "Draw" },
    { id: "image", icon: Image, label: "Image" },
    { id: "camera", icon: Camera, label: "Camera" },
    { id: "video", icon: Video, label: "Video" },
    { id: "music", icon: Music, label: "Music" },
    { id: "headphones", icon: Headphones, label: "Audio" },
    { id: "mic", icon: Mic, label: "Podcast" },
    { id: "play", icon: Play, label: "Play" },
    // Communication
    { id: "mail", icon: Mail, label: "Email" },
    { id: "message-circle", icon: MessageCircle, label: "Chat" },
    { id: "phone", icon: Phone, label: "Phone" },
    { id: "megaphone", icon: Megaphone, label: "Marketing" },
    { id: "send", icon: Send, label: "Send" },
    { id: "bell", icon: Bell, label: "Notifications" },
    // Organization
    { id: "calendar", icon: Calendar, label: "Calendar" },
    { id: "clock", icon: Clock, label: "Time" },
    { id: "timer", icon: Timer, label: "Timer" },
    { id: "clipboard", icon: Clipboard, label: "Tasks" },
    { id: "inbox", icon: Inbox, label: "Inbox" },
    { id: "archive", icon: Archive, label: "Archive" },
    { id: "tag", icon: Tag, label: "Tag" },
    { id: "layers", icon: Layers, label: "Layers" },
    { id: "layout", icon: Layout, label: "Layout" },
    // Tools
    { id: "settings", icon: Settings, label: "Settings" },
    { id: "cog", icon: Cog, label: "Config" },
    { id: "wrench", icon: Wrench, label: "Tools" },
    { id: "hammer", icon: Hammer, label: "Build" },
    { id: "scissors", icon: Scissors, label: "Cut" },
    { id: "ruler", icon: Ruler, label: "Measure" },
    { id: "wand", icon: Wand, label: "Magic" },
    // Nature
    { id: "sun", icon: Sun, label: "Sun" },
    { id: "moon", icon: Moon, label: "Moon" },
    { id: "leaf", icon: Leaf, label: "Eco" },
    { id: "flower", icon: Flower, label: "Flower" },
    { id: "tree", icon: TreeDeciduous, label: "Tree" },
    { id: "mountain", icon: Mountain, label: "Mountain" },
    { id: "droplet", icon: Droplet, label: "Water" },
    { id: "flame", icon: Flame, label: "Fire" },
    { id: "snowflake", icon: Snowflake, label: "Winter" },
    { id: "rainbow", icon: Rainbow, label: "Rainbow" },
    // Other
    { id: "home", icon: Home, label: "Home" },
    { id: "key", icon: Key, label: "Key" },
    { id: "lock", icon: Lock, label: "Lock" },
    { id: "shield", icon: Shield, label: "Security" },
    { id: "award", icon: Award, label: "Award" },
    { id: "crown", icon: Crown, label: "Premium" },
    { id: "gem", icon: Gem, label: "Gem" },
    { id: "diamond", icon: Diamond, label: "Diamond" },
    { id: "gift", icon: Gift, label: "Gift" },
    { id: "cake", icon: Cake, label: "Birthday" },
    { id: "coffee", icon: Coffee, label: "Coffee" },
    { id: "wine", icon: Wine, label: "Wine" },
    { id: "puzzle", icon: Puzzle, label: "Puzzle" },
    { id: "gamepad", icon: Gamepad2, label: "Gaming" },
    { id: "dumbbell", icon: Dumbbell, label: "Fitness" },
    { id: "book", icon: Book, label: "Book" },
    { id: "book-open", icon: BookOpen, label: "Reading" },
    { id: "library", icon: Library, label: "Library" },
    { id: "university", icon: University, label: "Education" },
    { id: "beaker", icon: Beaker, label: "Science" },
    { id: "flask", icon: FlaskConical, label: "Lab" },
    { id: "map", icon: Map, label: "Map" },
    { id: "compass", icon: Compass, label: "Navigate" },
    { id: "plane", icon: Plane, label: "Travel" },
    { id: "watch", icon: Watch, label: "Watch" },
    { id: "truck", icon: Truck, label: "Delivery" },
    { id: "package", icon: Package, label: "Package" },
    { id: "box", icon: Box, label: "Box" },
    { id: "sparkles", icon: Sparkles, label: "Sparkles" },
    { id: "activity", icon: Activity, label: "Activity" },
    { id: "pie-chart", icon: PieChart, label: "Analytics" },
    { id: "search", icon: Search, label: "Search" },
    { id: "thumbs-up", icon: ThumbsUp, label: "Like" },
    { id: "smile", icon: Smile, label: "Happy" },
    { id: "heart-pulse", icon: HeartPulse, label: "Health" },
    { id: "life-buoy", icon: LifeBuoy, label: "Support" },
  ];

// Get icon component by id
export const getProjectIcon = (iconId: string | null | undefined) => {
  const iconConfig = PROJECT_ICONS.find((i) => i.id === iconId);
  return iconConfig?.icon || PROJECT_ICONS[0].icon;
};

// Get icon config by id
export const getProjectIconConfig = (iconId: string | null | undefined) => {
  return PROJECT_ICONS.find((i) => i.id === iconId) || PROJECT_ICONS[0];
};
